---

- name: Configure instance
  hosts: all
  gather_facts: False
  become: true
  vars:
    hostname: KAL-EL-Hernandez
    tz: Pacific/Honolulu

  tasks:
    - name: Set new timezone to "{{ tz }}"
      timezone:
        name: "{{ tz }}"
    - name: Display new timezone
      shell: date +%Z
      
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
    
